// pakistanPack.js — Curated Pakistan Culture Quest content pack.
//
// All word pools are hand-curated (not AI-generated) so judges and
// players never see incorrect / inappropriate Pakistan facts. Each
// category ships with: a word list (4–11 letters, uppercase), an
// emoji, a one-line description, and per-word tutor notes (English
// + Roman Urdu) for the TutorAgent.
//
// Pool sizing rule of thumb: ≥25 words per category, balanced across
// length buckets (4–6 / 5–8 / 6–10) so the adaptive difficulty agent
// can serve fresh non-repeated puzzles for 10+ games per section at
// every difficulty level.

const CATEGORIES = [
  {
    key: 'cities',
    name: 'Pakistan Cities',
    emoji: '🏙️',
    description: 'Famous cities across the four provinces.',
    words: [
      { word: 'KARACHI',    en: 'Karachi is the largest city of Pakistan and a major port on the Arabian Sea.',           ur: 'Karachi Pakistan ka sab se bara shehar aur Arabian Sea ka aham bandar hai.' },
      { word: 'LAHORE',     en: 'Lahore is the cultural heart of Pakistan and capital of Punjab province.',                ur: 'Lahore Pakistan ka saqafati markaz aur Punjab ka darulhukumat hai.' },
      { word: 'MULTAN',     en: 'Multan is one of the oldest cities of South Asia, known as the "City of Saints".',         ur: 'Multan jonubi Asia ka qadeem tareen shehar hai, "Auliya ka Shehar" kehlata hai.' },
      { word: 'QUETTA',     en: 'Quetta is the capital of Balochistan, famous for its dry fruit and apples.',                ur: 'Quetta Balochistan ka darulhukumat hai, khushk meva aur seb ke liye mashhoor hai.' },
      { word: 'PESHAWAR',   en: 'Peshawar is the capital of KPK, an ancient city on the historic Silk Road.',                ur: 'Peshawar KPK ka darulhukumat hai aur tareekhi Silk Road par waqe hai.' },
      { word: 'SIALKOT',    en: 'Sialkot is famous worldwide for sports goods, surgical instruments and leather.',           ur: 'Sialkot khel ke saaman, jarrahi auzaar aur charmsaazi ke liye dunyaa bhar mein mashhoor hai.' },
      { word: 'GUJRANWALA', en: 'Gujranwala is a major industrial city of Punjab — "City of Wrestlers".',                    ur: 'Gujranwala Punjab ka aham sanati shehar hai, "Pehlwano ka Shehar" kehlata hai.' },
      { word: 'HYDERABAD',  en: 'Hyderabad in Sindh is famous for its glass bangles and Sindhi handicrafts.',                ur: 'Hyderabad (Sindh) shisha churyon aur sindhi dastkari ke liye mashhoor hai.' },
      { word: 'FAISALABAD', en: 'Faisalabad is the textile hub of Pakistan and the country\'s third-largest city.',          ur: 'Faisalabad Pakistan ka textile markaz aur mulk ka teesra sab se bara shehar hai.' },
      { word: 'ISLAMABAD',  en: 'Islamabad is the modern capital of Pakistan, planned in the 1960s.',                        ur: 'Islamabad Pakistan ka jadeed darulhukumat hai, 1960 ki dahaayi mein banaya gaya.' },
      { word: 'MURREE',     en: 'Murree is a popular hill station near Islamabad, famous for snow in winter.',               ur: 'Murree Islamabad ke qareeb mashhoor pahari maqaam hai, sardiyon mein barf ke liye mashhoor.' },
      { word: 'SWAT',       en: 'Swat is a scenic valley in KPK, often called the "Switzerland of Pakistan".',               ur: 'Swat KPK ki khoobsoorat waadi hai, "Switzerland of Pakistan" kehlati hai.' },
      { word: 'SKARDU',     en: 'Skardu is a high-altitude town in Gilgit-Baltistan, gateway to K2.',                         ur: 'Skardu Gilgit-Baltistan ka oncha shehar hai, K2 ka darwaza.' },
      { word: 'HUNZA',      en: 'Hunza is a mountain valley famous for its long-lived people and apricots.',                  ur: 'Hunza pahaari waadi hai, lambi umar aur khubaani ke liye mashhoor.' },
      { word: 'GILGIT',     en: 'Gilgit is the capital of Gilgit-Baltistan, surrounded by towering mountains.',               ur: 'Gilgit Gilgit-Baltistan ka darulhukumat hai, oonchay pahaaron mein ghira.' },
      { word: 'GWADAR',     en: 'Gwadar is a coastal city with a deep-sea port developed under CPEC.',                        ur: 'Gwadar sahil ka shehar hai, CPEC ke tahat deep-sea port banaya gaya.' },
      { word: 'CHITRAL',    en: 'Chitral is a beautiful mountain district in KPK, home to the Kalash people.',                ur: 'Chitral KPK ka khoobsoorat pahaari zilaa hai, yahan Kalash log rehte hain.' },
      { word: 'BAHAWALPUR', en: 'Bahawalpur is famous for the Cholistan desert, Derawar fort and Noor Mahal palace.',         ur: 'Bahawalpur Cholistan registan, Derawar qila aur Noor Mahal ke liye mashhoor hai.' },
      { word: 'SUKKUR',     en: 'Sukkur is a major Sindh city on the Indus, famous for the Lansdowne Bridge.',                ur: 'Sukkur Sindh ka aham shehar hai, Sindh darya par Lansdowne Bridge ke liye mashhoor.' },
      { word: 'LARKANA',    en: 'Larkana is a historic Sindh city near the ancient Mohenjo-daro ruins.',                      ur: 'Larkana Sindh ka tareekhi shehar hai, qadeem Mohenjo-daro ke qareeb.' },
      { word: 'ABBOTABAD',  en: 'Abbottabad is a hill town in KPK known for its pleasant climate and military academy.',      ur: 'Abbottabad KPK ka pahaari shehar hai, mausam aur military academy ke liye mashhoor.' },
      { word: 'MARDAN',     en: 'Mardan is a city in KPK famous for its ancient Buddhist Gandhara sites.',                    ur: 'Mardan KPK ka shehar hai, qadeem Buddhist Gandhara maqaamat ke liye mashhoor.' },
      { word: 'SAHIWAL',    en: 'Sahiwal is a Punjab city famous for its cattle breed and agricultural produce.',             ur: 'Sahiwal Punjab ka shehar hai, gaaye ki nasal aur zarayi paidawar ke liye mashhoor.' },
      { word: 'OKARA',      en: 'Okara is a Punjab city known for its dairy and military farms.',                              ur: 'Okara Punjab ka shehar hai, dairy aur military farms ke liye mashhoor.' },
      { word: 'JHELUM',     en: 'Jhelum is a Punjab city on the Jhelum river, with a rich military tradition.',               ur: 'Jhelum darya-e-Jhelum par Punjab ka shehar hai, foji tareekh ke liye mashhoor.' },
      { word: 'KASUR',      en: 'Kasur is a historic Punjab city, birthplace of the poet Bulleh Shah.',                       ur: 'Kasur Punjab ka tareekhi shehar hai, shaayar Bulleh Shah ki jaaye paidaaish.' },
      { word: 'ATTOCK',     en: 'Attock sits where the Indus meets the Kabul river, near a famous Mughal fort.',              ur: 'Attock wahan hai jahan Indus aur Kabul darya milte hain, mashhoor Mughal qila ke qareeb.' },
      { word: 'THATTA',     en: 'Thatta in Sindh is famous for the Shah Jahan Mosque and Makli necropolis.',                  ur: 'Thatta Sindh mein Shah Jahan Masjid aur Makli qabristan ke liye mashhoor hai.' },
    ],
  },
  {
    key: 'food',
    name: 'Pakistani Food',
    emoji: '🍛',
    description: 'Iconic dishes loved across Pakistan.',
    words: [
      { word: 'BIRYANI',  en: 'Biryani is a fragrant rice dish layered with spiced meat — Karachi-style is most famous.', ur: 'Biryani masaledar gosht aur khushboo daar chawal ki dish hai. Karachi-style sab se mashhoor hai.' },
      { word: 'NIHARI',   en: 'Nihari is a slow-cooked beef stew, traditionally eaten for breakfast.',                    ur: 'Nihari dheeme aanch par pakaaya hua gaye/beef ka shorba hai, riwayati naashta.' },
      { word: 'HALEEM',   en: 'Haleem is a thick stew of meat, lentils and pounded wheat — Muharram favourite.',          ur: 'Haleem gosht, daal aur gandum se bana gaarha shorba hai, Muharram mein khaas mashhoor.' },
      { word: 'PULAO',    en: 'Pulao is a milder rice dish cooked in stock — lighter than biryani.',                      ur: 'Pulao yakhni mein pakaaye chawal hain — biryani ke muqabley halka.' },
      { word: 'KARAHI',   en: 'Karahi is a meat curry cooked in a wok with tomatoes, ginger and green chillies.',         ur: 'Karahi kadhayi mein tamatar, adrak aur hari mirch ke saath pakaaya gosht hai.' },
      { word: 'KEBAB',    en: 'Kebabs are grilled minced-meat skewers, popular street food.',                              ur: 'Kebab grill kiye gaye qeema ke seekh hain, mashhoor street food.' },
      { word: 'SAMOSA',   en: 'Samosa is a triangular fried pastry filled with spiced potato or meat.',                    ur: 'Samosa teen kone wala tala hua pastry, masaledar aloo ya qeema bhara hua.' },
      { word: 'PAKORA',   en: 'Pakora is a chickpea-flour fritter, eaten at iftar with chutney.',                          ur: 'Pakora besan ka pakwaan hai, aksar iftaari mein chutney ke saath kha-ya jata hai.' },
      { word: 'CHAPLI',   en: 'Chapli Kebab is a flat, spiced beef patty from Peshawar.',                                  ur: 'Chapli Kebab Peshawar ka chapta masaledar beef kebab hai.' },
      { word: 'KHEER',    en: 'Kheer is a creamy rice pudding cooked in milk with sugar and cardamom.',                    ur: 'Kheer doodh mein pakaaya hua chawal ka meetha hai, elaichi ki khushboo ke saath.' },
      { word: 'NAAN',     en: 'Naan is a soft tandoor-baked flatbread, eaten with curries.',                               ur: 'Naan tandoor mein paki narm roti hai, salan ke saath khaayi jaati hai.' },
      { word: 'ROTI',     en: 'Roti is a whole-wheat flatbread, eaten at almost every meal.',                              ur: 'Roti aate ki chapaati hai, qareeban hr khane ke saath khaayi jaati hai.' },
      { word: 'PARATHA',  en: 'Paratha is a flaky layered flatbread, often eaten at breakfast.',                           ur: 'Paratha parton waali roti hai, aam tor par naashte mein khaayi jaati hai.' },
      { word: 'CHANA',    en: 'Chana is a spiced chickpea curry, a popular breakfast across Pakistan.',                    ur: 'Chana masaledar chany hai, Pakistan mein mashhoor naashta.' },
      { word: 'DAAL',     en: 'Daal is a comforting lentil stew, a staple in every Pakistani home.',                       ur: 'Daal dilkash dalon ka pakwan hai, har ghar ka aam khana.' },
      { word: 'SAJJI',    en: 'Sajji is a whole roasted lamb or chicken from Balochistan, marinated in salt.',             ur: 'Sajji Balochistan ka pura bhuna hua dumba ya chicken hai, namak mein marinate.' },
      { word: 'GULAB',    en: 'Gulab Jamun is a deep-fried milk-solid ball soaked in rose-cardamom syrup.',                ur: 'Gulab Jamun talee hui khoye ki goli hai, gulab-elaichi sheere mein.' },
      { word: 'JALEBI',   en: 'Jalebi is a coiled crisp sweet soaked in saffron syrup, often eaten warm.',                 ur: 'Jalebi guthli huyi khasta meethi hai, zafrani sheere mein dabaayi jaati hai.' },
      { word: 'FALOODA',  en: 'Falooda is a chilled dessert drink with vermicelli, basil seeds and ice cream.',            ur: 'Falooda thanda meetha drink hai, sev, tukhmalanga aur ice cream ke saath.' },
      { word: 'LASSI',    en: 'Lassi is a refreshing yoghurt drink, sweet or salty, perfect for summer.',                  ur: 'Lassi dahi ka thanda drink hai, meethi ya namkeen, garmiyon ke liye behtareen.' },
      { word: 'CHAAT',    en: 'Chaat is a tangy mix of chickpeas, potatoes and chutneys — popular street snack.',          ur: 'Chaat chany, aloo aur chutniyo ka chatpata mix hai, mashhoor street snack.' },
      { word: 'GOLGAPPA', en: 'Gol Gappay are crispy hollow shells filled with spicy tamarind water.',                     ur: 'Gol Gappay khoklay khasta khol hain, teekhe imli paani se bhare jaate hain.' },
      { word: 'QORMA',    en: 'Korma is a rich gravy of meat slow-cooked with yoghurt, spices and onions.',                ur: 'Korma dahi, masalon aur pyaaz ke saath dheere pakaaya gosht ka rich gravy hai.' },
      { word: 'TIKKA',    en: 'Tikka is marinated meat skewered and grilled — a classic Pakistani BBQ item.',              ur: 'Tikka masaledar gosht ke tukde seekh par grill kiye jaate hain, classic Pakistani BBQ.' },
      { word: 'ROOHAFZA', en: 'Rooh Afza is a rose-flavoured sherbet, the iconic Ramadan drink.',                          ur: 'Rooh Afza gulab-mehek sharbat hai, Ramazan ka mashhoor drink.' },
      { word: 'BARFI',    en: 'Barfi is a milk fudge sweet, often topped with silver leaf and pistachios.',                ur: 'Barfi khoye ki meethi hai, chandi ka warq aur pista ke saath.' },
      { word: 'LADDU',    en: 'Laddu is a round sweet made of gram flour, sugar and ghee.',                                ur: 'Laddu besan, cheeni aur ghee se bani goal meethi hai.' },
      // FRUITS — Pakistan is famous for its summer fruits.
      { word: 'MANGO',    en: 'Mango is the national fruit of Pakistan, sweetest in summer.',                              ur: 'Aam Pakistan ka qaumi phal hai, garmi mein sab se meetha.' },
      { word: 'APPLE',    en: 'Apples grow in the cool hills of Quetta, Swat and Gilgit-Baltistan.',                       ur: 'Seb Pakistan ke thande pahaadi ilaqon mein paida hote hain.' },
      { word: 'ORANGE',   en: 'Oranges (Kinnow) are a popular winter fruit from Sargodha.',                                ur: 'Orange Sargodha mashhoor hai, sardiyon ka phal.' },
      { word: 'BANANA',   en: 'Bananas are grown in southern Pakistan and eaten year-round.',                              ur: 'Kelay janoob mein paida hote hain, saara saal khaaye jaate hain.' },
      { word: 'GRAPES',   en: 'Grapes are popular fresh and as sun-dried raisins.',                                        ur: 'Angoor taaza aur munaqqa ke tor par pasand kiya jaata hai.' },
      { word: 'PEACH',    en: 'Peaches grow in Swat and the northern valleys.',                                            ur: 'Aaru Swat aur shumaali waadi mein paida hote hain.' },
      { word: 'CHERRY',   en: 'Cherries from Hunza and Gilgit are loved for their sweet juice.',                           ur: 'Hunza aur Gilgit ki cherries meethi ras ke liye mashhoor hain.' },
      { word: 'GUAVA',    en: 'Guava is a fragrant winter fruit, often eaten with salt and chilli.',                       ur: 'Amrood sardiyon ka phal hai, namak mirch ke saath khaaya jaata hai.' },
      // VEGETABLES
      { word: 'POTATO',   en: 'Potatoes are the most common vegetable in Pakistani cooking.',                              ur: 'Aloo sab se aam Pakistani sabzi hai.' },
      { word: 'ONION',    en: 'Onions form the base of almost every Pakistani curry.',                                     ur: 'Pyaaz qareeban hr salan ki bunyaad hai.' },
      { word: 'CARROT',   en: 'Carrots are eaten fresh, in salads, and made into sweet halwa.',                            ur: 'Gajar taaza, salad mein aur meetha halwa mein use hoti hai.' },
      { word: 'TOMATO',   en: 'Tomatoes give curries their rich red colour and tangy taste.',                              ur: 'Tamatar salan ko surkh rang aur khaata zaaiqa deta hai.' },
      { word: 'SPINACH',  en: 'Spinach (palak) is often paired with paneer or meat.',                                      ur: 'Palak paneer ya gosht ke saath khaayi jaati hai.' },
      // DRY FRUITS
      { word: 'ALMOND',   en: 'Almonds are a snack and used in Pakistani sweets.',                                         ur: 'Badaam snack aur Pakistani mithaaiyon mein use hote hain.' },
      { word: 'CASHEW',   en: 'Cashews are popular in milk sweets and rice dishes.',                                       ur: 'Kaaju doodh ki mithaaiyon aur chawal mein use hote hain.' },
      { word: 'WALNUT',   en: 'Walnuts grow in the northern areas and add crunch to halwas.',                              ur: 'Akhrot shumaali ilaqon mein hote hain, halwon mein karara dete hain.' },
      { word: 'RAISIN',   en: 'Raisins are sun-dried grapes, used in pulao and desserts.',                                  ur: 'Munaqqa sookhe angoor hain, pulao aur mithaaiyon mein use hote hain.' },
      { word: 'PISTACHIO',en: 'Pistachios are added to kheer, kulfi and barfi for flavour.',                               ur: 'Pista kheer, kulfi aur barfi mein zaaiqe ke liye daala jaata hai.' },
      // FAST FOOD
      { word: 'PIZZA',    en: 'Pizza is a popular fast food across Pakistan today.',                                       ur: 'Pizza aaj Pakistan mein mashhoor fast food hai.' },
      { word: 'BURGER',   en: 'Burgers from local chains are a favourite snack for kids.',                                 ur: 'Burger Pakistani bachon ka pasandeeda snack hai.' },
      { word: 'FRIES',    en: 'French fries are a popular side dish across Pakistan.',                                     ur: 'Fries Pakistan mein har jagah pasand kiye jaate hain.' },
      { word: 'SHAWARMA', en: 'Shawarma is a Middle-Eastern roll, now very popular in Pakistan.',                          ur: 'Shawarma Middle-Eastern roll hai, Pakistan mein bohot mashhoor hai.' },
      { word: 'KETCHUP',  en: 'Tomato ketchup is the favourite Pakistani fast-food dip.',                                  ur: 'Tomato ketchup Pakistani fast food ka pasandeeda dip hai.' },
      { word: 'NOODLES',  en: 'Instant noodles are a quick after-school snack for kids.',                                  ur: 'Noodles bachon ka school ke baad ka mashhoor snack hai.' },
      { word: 'PASTA',    en: 'Pasta is a popular dish in restaurants across Pakistan.',                                   ur: 'Pasta Pakistani restaurants mein mashhoor dish hai.' },
      { word: 'CHICKEN',  en: 'Chicken is the most common protein in Pakistani meals.',                                    ur: 'Murghi Pakistani khaane mein sab se aam gosht hai.' },
      { word: 'CHEESE',   en: 'Cheese is used in burgers, sandwiches and many fast foods.',                                ur: 'Cheese burger, sandwich aur fast food mein use hota hai.' },
    ],
  },
  {
    key: 'sports',
    name: 'Cricket Heroes',
    emoji: '🏏',
    description: 'Pakistan cricket legends and current stars.',
    words: [
      { word: 'IMRAN',    en: 'Imran Khan captained Pakistan to the 1992 Cricket World Cup victory.',                      ur: 'Imran Khan ne Pakistan ko 1992 ka Cricket World Cup jeetwaaya.' },
      { word: 'AKRAM',    en: 'Wasim Akram, the "Sultan of Swing", is one of the greatest fast bowlers ever.',             ur: 'Wasim Akram "Sultan of Swing" — duniya ke mahaan tareen fast bowlers mein se ek.' },
      { word: 'WAQAR',    en: 'Waqar Younis was known for devastating yorkers and reverse swing.',                         ur: 'Waqar Younis tabaahkun yorker aur reverse swing ke liye mashhoor the.' },
      { word: 'AFRIDI',   en: 'Shahid Afridi (Boom Boom) hit the fastest ODI century of his time.',                        ur: 'Shahid Afridi (Boom Boom) ne apne daur ki sab se tez ODI century lagayi.' },
      { word: 'MISBAH',   en: 'Misbah-ul-Haq led Pakistan to the No. 1 Test ranking in 2016.',                              ur: 'Misbah-ul-Haq ne 2016 mein Pakistan ko Test ranking mein No. 1 banaya.' },
      { word: 'BABAR',    en: 'Babar Azam is a modern Pakistan batting star and former captain.',                          ur: 'Babar Azam Pakistan ka modern batting star aur sabiq kaptaan hai.' },
      { word: 'RIZWAN',   en: 'Mohammad Rizwan is a top-class wicketkeeper-batsman.',                                       ur: 'Mohammad Rizwan top class wicketkeeper-batsman hai.' },
      { word: 'SHAHEEN',  en: 'Shaheen Shah Afridi is one of the world\'s fastest left-arm pacers today.',                  ur: 'Shaheen Shah Afridi aaj duniya ke sab se tez left-arm pacers mein se ek hai.' },
      { word: 'INZAMAM',  en: 'Inzamam-ul-Haq scored over 8,800 Test runs and captained Pakistan.',                         ur: 'Inzamam-ul-Haq ne 8,800+ Test runs banaye aur Pakistan ke kaptaan rahe.' },
      { word: 'YOUNIS',   en: 'Younis Khan is Pakistan\'s highest Test run-scorer of all time.',                            ur: 'Younis Khan Pakistan ke har waqt ke sab se zyada Test run scorer hain.' },
      { word: 'JAVED',    en: 'Javed Miandad hit the iconic last-ball six against India in 1986 at Sharjah.',              ur: 'Javed Miandad ne 1986 Sharjah mein India ke khilaaf last-ball six maara.' },
      { word: 'SAEED',    en: 'Saeed Anwar held the highest ODI score (194) for many years.',                              ur: 'Saeed Anwar ka 194 saalon tak sab se zyada ODI score raha.' },
      { word: 'YOUHANA',  en: 'Yousuf Youhana (Mohammad Yousuf) broke a Test runs record in 2006.',                        ur: 'Yousuf Youhana (Mohammad Yousuf) ne 2006 mein Test runs ka record toda.' },
      { word: 'AAMIR',    en: 'Mohammad Aamir is a left-arm fast bowler known for swing and accuracy.',                   ur: 'Mohammad Aamir left-arm fast bowler hain, swing aur accuracy ke liye mashhoor.' },
      { word: 'HARIS',    en: 'Haris Rauf is a Pakistani express pacer famous for raw pace.',                              ur: 'Haris Rauf Pakistani express pacer hain, kaachi pace ke liye mashhoor.' },
      { word: 'NASEEM',   en: 'Naseem Shah is a young Pakistan pacer who debuted as a teenager.',                          ur: 'Naseem Shah Pakistan ke nau-umar pacer hain, teenager mein debut kiya.' },
      { word: 'HASAN',    en: 'Hasan Ali is a right-arm fast bowler celebrated for his trademark celebration.',            ur: 'Hasan Ali right-arm fast bowler hain, signature celebration ke liye mashhoor.' },
      { word: 'FAKHAR',   en: 'Fakhar Zaman is a hard-hitting left-handed opener.',                                        ur: 'Fakhar Zaman left-handed taqatwar opener hain.' },
      { word: 'SARFARAZ', en: 'Sarfaraz Ahmed captained Pakistan to the 2017 ICC Champions Trophy title.',                  ur: 'Sarfaraz Ahmed ne 2017 ICC Champions Trophy mein Pakistan ki qiyaadat ki.' },
      { word: 'SHADAB',   en: 'Shadab Khan is an all-rounder, leg-spinner and Pakistan vice-captain.',                     ur: 'Shadab Khan all-rounder, leg-spinner aur Pakistan ke vice-captain hain.' },
      { word: 'IFTIKHAR', en: 'Iftikhar Ahmed is a powerful middle-order batter and useful off-spinner.',                  ur: 'Iftikhar Ahmed taqatwar middle-order batter aur kaarisazi off-spinner hain.' },
      { word: 'WAHAB',    en: 'Wahab Riaz is a left-arm fast bowler famous for a hostile spell vs Australia in 2015.',     ur: 'Wahab Riaz left-arm fast bowler hain, 2015 mein Australia ke khilaaf khaufnaak spell ke liye mashhoor.' },
      { word: 'UMAR',     en: 'Umar Akmal is a stylish middle-order batter.',                                              ur: 'Umar Akmal stylish middle-order batter hain.' },
      { word: 'MOHSIN',   en: 'Mohsin Khan was a stylish opener who led Pakistan in the 1980s.',                           ur: 'Mohsin Khan 1980 ki dahaayi ke stylish opener the, kaptaan bhi rahe.' },
      { word: 'ABDUL',    en: 'Abdul Qadir was the leg-spin wizard who revived the art in the 1980s.',                     ur: 'Abdul Qadir leg-spin ke jaadugar the, 1980 mein leg-spin ko zinda kiya.' },
    ],
  },
  {
    key: 'heroes',
    name: 'National Heroes',
    emoji: '⭐',
    description: 'Leaders, reformers and changemakers.',
    words: [
      { word: 'JINNAH',   en: 'Muhammad Ali Jinnah, Quaid-e-Azam, was the founder of Pakistan.',                            ur: 'Muhammad Ali Jinnah, Quaid-e-Azam, Pakistan ke baani-e-mulk hain.' },
      { word: 'IQBAL',    en: 'Allama Iqbal was a poet-philosopher who first dreamt of a separate Muslim homeland.',       ur: 'Allama Iqbal woh shaayar-falsafi the jinhone alag Muslim watan ka khwaab dekha.' },
      { word: 'LIAQAT',   en: 'Liaquat Ali Khan was Pakistan\'s first Prime Minister.',                                     ur: 'Liaquat Ali Khan Pakistan ke pehle wazeer-e-azam the.' },
      { word: 'FATIMA',   en: 'Fatima Jinnah, "Madar-e-Millat", was Quaid\'s sister and a freedom-movement leader.',        ur: 'Fatima Jinnah "Madar-e-Millat" — Quaid ki behan aur tehreek-e-azaadi ki rehnuma.' },
      { word: 'EDHI',     en: 'Abdul Sattar Edhi ran the world\'s largest volunteer ambulance service.',                    ur: 'Abdul Sattar Edhi ne duniya ki sab se badi volunteer ambulance service chalayi.' },
      { word: 'MALALA',   en: 'Malala Yousafzai won the Nobel Peace Prize for her education activism.',                     ur: 'Malala Yousafzai ko taleem ke liye Nobel Peace Prize mila.' },
      { word: 'SALAM',    en: 'Dr. Abdus Salam was Pakistan\'s first Nobel laureate (Physics, 1979).',                      ur: 'Dr. Abdus Salam Pakistan ke pehle Nobel laureate the (Physics, 1979).' },
      { word: 'QADEER',   en: 'Dr. Abdul Qadeer Khan was a key figure in Pakistan\'s nuclear program.',                     ur: 'Dr. Abdul Qadeer Khan Pakistan ke nuclear program ke aham scientist the.' },
      { word: 'BHUTTO',   en: 'Zulfikar Ali Bhutto served as Prime Minister and President of Pakistan in the 1970s.',       ur: 'Zulfikar Ali Bhutto 1970 ki dahaayi mein Pakistan ke wazeer-e-azam aur sadr rahe.' },
      { word: 'BENAZIR',  en: 'Benazir Bhutto became the first female Prime Minister of a Muslim-majority country.',        ur: 'Benazir Bhutto kisi Muslim akhsariati mulk ki pehli khatoon wazeer-e-azam thin.' },
      { word: 'AYUB',     en: 'Field Marshal Ayub Khan was a military ruler who modernised Pakistan in the 1960s.',         ur: 'Field Marshal Ayub Khan foji hukmaraan the, 1960 ki dahaayi mein Pakistan ko modern banaya.' },
      { word: 'ARFA',     en: 'Arfa Karim was the youngest Microsoft Certified Professional at age 9.',                      ur: 'Arfa Karim 9 saal ki umr mein sab se nau-umar Microsoft Certified Professional bani.' },
      { word: 'SADEQUAIN',en: 'Sadequain was a celebrated calligrapher and painter of Pakistan.',                            ur: 'Sadequain Pakistan ke namwar khattat aur musawwir the.' },
      { word: 'FAIZ',     en: 'Faiz Ahmad Faiz was a beloved Urdu poet known for social-justice themes.',                    ur: 'Faiz Ahmad Faiz Urdu ke pyaarey shaayar the, samaaji insaaf ke shayar.' },
      { word: 'NUSRAT',   en: 'Nusrat Fateh Ali Khan brought Sufi Qawwali music to global audiences.',                       ur: 'Nusrat Fateh Ali Khan ne Sufi qawwali ko duniya bhar tak pohanchaaya.' },
      { word: 'NAZIA',    en: 'Nazia Hassan was a beloved pop singer who shaped South Asian pop music.',                     ur: 'Nazia Hassan South Asian pop ki banaani thi.' },
      { word: 'GHALIB',   en: 'Mirza Ghalib was a giant of Urdu poetry whose verses still inspire millions.',                ur: 'Mirza Ghalib Urdu shaayri ke aazeem shaayar the.' },
      { word: 'MANTO',    en: 'Saadat Hasan Manto wrote unforgettable short stories about Partition.',                        ur: 'Saadat Hasan Manto ne Taqseem-e-Hind par yaadgaar afsaaney likhe.' },
      { word: 'RUTH',     en: 'Ruth Pfau spent her life serving leprosy patients in Pakistan.',                               ur: 'Ruth Pfau ne apni zindagi Pakistan mein juzaam ke mareezo ki khidmat mein guzaari.' },
      // MILITARY HEROES — Nishan-e-Haider awardees and iconic generals
      { word: 'BHATTI',   en: 'Major Aziz Bhatti was awarded Nishan-e-Haider for valour in the 1965 war.',                   ur: 'Major Aziz Bhatti ko 1965 ki jang mein bahaduri par Nishan-e-Haider mila.' },
      { word: 'MINHAS',   en: 'Pilot Officer Rashid Minhas earned Nishan-e-Haider in 1971.',                                  ur: 'Pilot Officer Rashid Minhas ko 1971 mein Nishan-e-Haider mila.' },
      { word: 'SHABBIR',  en: 'Captain Shabbir Sharif earned Nishan-e-Haider for bravery in 1971.',                          ur: 'Captain Shabbir Sharif ko 1971 mein bahaduri par Nishan-e-Haider mila.' },
      { word: 'RAHEEL',   en: 'General Raheel Sharif served as the Chief of Army Staff (2013-2016).',                        ur: 'General Raheel Sharif Pakistan army ke chief rahe (2013-2016).' },
      // SPORTS LEGENDS — beyond cricket
      { word: 'JAHANGIR', en: 'Jahangir Khan won the World Open squash title six times.',                                    ur: 'Jahangir Khan ne 6 baar World Open squash jeeti.' },
      { word: 'HASHIM',   en: 'Hashim Khan was a legendary Pakistani squash champion of the 1950s.',                         ur: 'Hashim Khan 1950 ki dahaayi ke Pakistani squash champion the.' },
      { word: 'JANSHER',  en: 'Jansher Khan won 8 World Open squash titles for Pakistan.',                                   ur: 'Jansher Khan ne Pakistan ke liye 8 World Open squash titles jeete.' },
      { word: 'AISAM',    en: 'Aisam-ul-Haq Qureshi is a Pakistani tennis star who reached the US Open finals.',             ur: 'Aisam-ul-Haq Qureshi Pakistan ke tennis star hain, US Open final tak pohanchay.' },
      { word: 'IMRAN',    en: 'Imran Khan led Pakistan to the 1992 World Cup and later served as Prime Minister.',           ur: 'Imran Khan ne 1992 World Cup jeeta aur baad mein Pakistan ke wazeer-e-azam bhi rahe.' },
      // SCIENTISTS & LITERATURE
      { word: 'ATTA',     en: 'Atta-ur-Rahman is a famous Pakistani chemist and former HEC chairman.',                       ur: 'Atta-ur-Rahman Pakistan ke mashhoor chemist aur HEC ke sabiq chairman hain.' },
      { word: 'BANO',     en: 'Bano Qudsia was a celebrated Urdu novelist and playwright.',                                  ur: 'Bano Qudsia Urdu ki namwar novelist aur playwright thin.' },
      { word: 'PARWEEN',  en: 'Parween Shakir was a beloved feminist Urdu poet.',                                            ur: 'Parween Shakir Urdu ki pyaari feminist shaayara thin.' },
      { word: 'TARIQ',    en: 'Tariq Aziz was a beloved broadcaster who hosted "Neelam Ghar" for decades.',                  ur: 'Tariq Aziz "Neelam Ghar" ke namwar broadcaster the.' },
      { word: 'SHARMEEN', en: 'Sharmeen Obaid-Chinoy won two Academy Awards for her documentaries.',                         ur: 'Sharmeen Obaid-Chinoy ne 2 baar Academy Awards jeete.' },
      { word: 'MAHIRA',   en: 'Mahira Khan is a renowned Pakistani actress and UN goodwill ambassador.',                     ur: 'Mahira Khan namwar Pakistani aada-kara aur UN goodwill ambassador hain.' },
      { word: 'WASEEM',   en: 'Waseem Akram captained Pakistan and is one of the greatest fast bowlers.',                    ur: 'Waseem Akram Pakistan ke kaptaan aur mahaan tareen fast bowler the.' },
      { word: 'NOORJAHAN',en: 'Noor Jehan, Malika-e-Tarannum, was the Queen of Pakistani music.',                            ur: 'Noor Jehan, Malika-e-Tarannum, Pakistani musiqi ki shehzaadi thin.' },
      { word: 'MEHDI',    en: 'Mehdi Hassan was hailed as the King of Ghazal across South Asia.',                            ur: 'Mehdi Hassan ko South Asia mein Shahenshah-e-Ghazal kaha jaata tha.' },
      { word: 'WAHEED',   en: 'Waheed Murad was the chocolate hero of 1960s-70s Pakistani cinema.',                          ur: 'Waheed Murad 1960-70 ke daur ke Pakistani cinema ke chocolate hero the.' },
    ],
  },
  {
    key: 'inventions',
    name: 'Made in Pakistan',
    emoji: '🛠️',
    description: 'Pakistan-built inventions and engineering feats.',
    words: [
      { word: 'THUNDER',  en: 'JF-17 Thunder is a 4th-generation fighter jet co-developed by Pakistan.',                    ur: 'JF-17 Thunder Pakistan ka tayyar karda 4th-generation fighter jet hai.' },
      { word: 'AGOSTA',   en: 'PNS Agosta is a Pakistan-built submarine class for the Navy.',                                ur: 'PNS Agosta Pakistan ki tayyar karda submarine class hai.' },
      { word: 'SHAHEEN',  en: 'Shaheen is a series of Pakistan-built medium-range ballistic missiles.',                      ur: 'Shaheen Pakistan ke tayyar karda medium-range ballistic missiles ka silsila hai.' },
      { word: 'GHAURI',   en: 'Ghauri is a long-range ballistic missile developed by Pakistan.',                             ur: 'Ghauri Pakistan ka tayyar karda long-range ballistic missile hai.' },
      { word: 'TARBELA',  en: 'Tarbela Dam on the Indus is one of the world\'s largest earth-fill dams.',                    ur: 'Tarbela Dam Sindh darya par duniya ke sab se baray earth-fill dams mein hai.' },
      { word: 'MANGLA',   en: 'Mangla Dam is the second-largest dam in Pakistan, built on the Jhelum river.',                ur: 'Mangla Dam Pakistan ka doosra sab se bara dam hai, Jhelum darya par.' },
      { word: 'GWADAR',   en: 'Gwadar Port is a deep-sea port developed under CPEC.',                                        ur: 'Gwadar Port deep-sea port hai, CPEC ke tehet tayyar.' },
      { word: 'CPEC',     en: 'CPEC connects Gwadar to western China via roads, rail and energy projects.',                  ur: 'CPEC Gwadar ko maghribi China se sadkon, rail aur energy projects ke zariye milata hai.' },
      { word: 'BABUR',    en: 'Babur is a Pakistan-developed cruise missile with land-attack capability.',                   ur: 'Babur Pakistan ka tayyar karda cruise missile hai, land-attack capability ke saath.' },
      { word: 'RAAD',     en: 'Raad is an air-launched cruise missile developed by Pakistan.',                                ur: 'Raad Pakistan ka tayyar karda air-launched cruise missile hai.' },
      { word: 'NASR',     en: 'Nasr (Hatf-9) is a short-range tactical missile system.',                                      ur: 'Nasr (Hatf-9) short-range tactical missile system hai.' },
      { word: 'ABABEEL',  en: 'Ababeel is a medium-range ballistic missile system tested by Pakistan.',                      ur: 'Ababeel Pakistan ka medium-range ballistic missile system hai.' },
      { word: 'BURRAQ',   en: 'Burraq is a Pakistan-built armed unmanned aerial vehicle (drone).',                           ur: 'Burraq Pakistan ka banaya hua armed drone hai.' },
      { word: 'NESCOM',   en: 'NESCOM is Pakistan\'s premier defence-research organisation.',                                ur: 'NESCOM Pakistan ka aham defence research idara hai.' },
      { word: 'SUPARCO',  en: 'SUPARCO is Pakistan\'s national space agency, founded in 1961.',                              ur: 'SUPARCO Pakistan ka qaumi space idara hai, 1961 mein qaaim hua.' },
      { word: 'BADR',     en: 'Badr-1 was Pakistan\'s first indigenous satellite, launched in 1990.',                        ur: 'Badr-1 Pakistan ka pehla khud sakhta satellite tha, 1990 mein launch hua.' },
      { word: 'PAKSAT',   en: 'PAKSAT-1R is a communications satellite jointly developed with China.',                       ur: 'PAKSAT-1R China ke saath mil kar banaya gaya communications satellite hai.' },
      { word: 'ALKHALID', en: 'Al-Khalid is a main battle tank co-developed by Pakistan.',                                    ur: 'Al-Khalid Pakistan ka banaya hua main battle tank hai.' },
      { word: 'KHALID',   en: 'Khalid (Al-Khalid) MBT is a workhorse of the Pakistan Army Armoured Corps.',                  ur: 'Khalid (Al-Khalid) MBT Pakistan army ke armoured corps ka aham tank hai.' },
      { word: 'CHASNUPP', en: 'CHASNUPP is a Chinese-assisted nuclear power station near Chashma.',                          ur: 'CHASNUPP Chashma ke qareeb Chinese-assisted nuclear power station hai.' },
      { word: 'KANUPP',   en: 'KANUPP, in Karachi, was Pakistan\'s first commercial nuclear power plant.',                   ur: 'KANUPP Karachi mein Pakistan ka pehla commercial nuclear power plant tha.' },
      { word: 'WARSAK',   en: 'Warsak Dam on the Kabul river was one of Pakistan\'s earliest hydro projects.',                ur: 'Warsak Dam darya-e-Kabul par Pakistan ka aik aham hydro project tha.' },
      { word: 'NEELUM',   en: 'Neelum-Jhelum Hydropower Project supplies major electricity to Pakistan.',                    ur: 'Neelum-Jhelum hydropower project Pakistan ko bohot bijli faraham karta hai.' },
      { word: 'DIAMER',   en: 'Diamer-Bhasha Dam on the Indus is a major Pakistan engineering megaproject.',                  ur: 'Diamer-Bhasha Dam Sindh darya par Pakistan ka aham engineering mega project hai.' },
      { word: 'MOTORWAY', en: 'The M-2 Motorway was one of South Asia\'s first modern motorways.',                            ur: 'M-2 Motorway South Asia ke pehle jadeed motorways mein se ek tha.' },
      // CONSUMER PRODUCTS — things Pakistan exports and is famous for making
      { word: 'FOOTBALL', en: 'Sialkot makes most of the world\'s hand-stitched footballs, including FIFA World Cup balls.', ur: 'Duniya ki zyada-tar footballs Sialkot mein banti hain, FIFA World Cup ki bhi.' },
      { word: 'BASMATI',  en: 'Basmati is Pakistan\'s long-grain aromatic rice, exported worldwide.',                        ur: 'Basmati Pakistan ka mashhoor lambay daana ka chawal hai, duniya bhar mein export hota hai.' },
      { word: 'LEATHER',  en: 'Pakistan\'s leather industry exports jackets, gloves and bags to many countries.',            ur: 'Pakistan ki leather industry duniya ke kayi mulkon mein jackets, gloves aur bags export karti hai.' },
      { word: 'DENIM',    en: 'Pakistani factories supply denim jeans to major global brands.',                              ur: 'Pakistani factories duniya ke bare brands ko denim jeans supply karti hain.' },
      { word: 'COTTON',   en: 'Pakistani cotton is one of the finest in the world.',                                         ur: 'Pakistani cotton duniya ki sab se umda mein se hai.' },
      { word: 'TEXTILE',  en: 'Textile is Pakistan\'s largest export industry by value.',                                    ur: 'Textile Pakistan ki sab se badi export industry hai.' },
      { word: 'SURGICAL', en: 'Sialkot also makes surgical instruments used by doctors worldwide.',                          ur: 'Sialkot duniya bhar ke doctors ke surgical instruments bhi banata hai.' },
      { word: 'CARPET',   en: 'Hand-knotted Pakistani carpets are famous in international markets.',                         ur: 'Pakistani haath se buni carpets duniya bhar mein mashhoor hain.' },
      { word: 'PAKOLA',   en: 'Pakola is a Pakistani-made green-coloured ice-cream-soda drink.',                             ur: 'Pakola Pakistan ka green-colored ice cream soda drink hai.' },
      { word: 'TAPAL',    en: 'Tapal is a famous Pakistani tea brand known across South Asia.',                              ur: 'Tapal Pakistan ka mashhoor chai brand hai.' },
      { word: 'NESTLE',   en: 'Nestlé Pakistan makes Milkpak — most kids\' favourite tetra-pack milk.',                      ur: 'Nestlé Pakistan Milkpak banata hai, bachon ka pasandeeda tetra-pack milk.' },
      { word: 'SHEZAN',   en: 'Shezan is a Pakistani brand famous for juices and pickles.',                                  ur: 'Shezan juice aur achar ka mashhoor Pakistani brand hai.' },
      { word: 'NATIONAL', en: 'National Foods makes spices, sauces and ready meals seen in every Pakistani kitchen.',         ur: 'National Foods masale aur ready meals banata hai, hr Pakistani kitchen mein milta hai.' },
      { word: 'OLPER',    en: 'Olpers is a Pakistani dairy brand famous for milk and tea creamer.',                          ur: 'Olpers Pakistan ka dairy brand hai, doodh aur chai creamer ke liye mashhoor.' },
      { word: 'MARMI',    en: 'Marmi is a popular Pakistani biscuit brand loved by kids.',                                   ur: 'Marmi mashhoor Pakistani biscuit brand hai jo bachon ko bohot pasand hai.' },
      { word: 'COMMANDO', en: 'Cars like the Hino Bus Body and trucks decorated by Pakistani truck art are world-famous.',   ur: 'Pakistani truck art aur buses duniya bhar mein mashhoor hain.' },
    ],
  },
  {
    key: 'urdu',
    name: 'Urdu Vocabulary',
    emoji: '📜',
    description: 'Everyday Urdu words written in Roman script.',
    words: [
      { word: 'KITAB',    en: '"Kitab" means book.',                                  ur: 'Kitab ka matlab hai book.' },
      { word: 'KHANA',    en: '"Khana" means food / meal.',                            ur: 'Khana ka matlab khaana ya meal hai.' },
      { word: 'BARISH',   en: '"Barish" means rain.',                                  ur: 'Barish ka matlab hai rain.' },
      { word: 'DARWAZA',  en: '"Darwaza" means door.',                                 ur: 'Darwaza ka matlab door.' },
      { word: 'JANGAL',   en: '"Jangal" means jungle / forest.',                       ur: 'Jangal ka matlab jungle ya forest.' },
      { word: 'BAGH',     en: '"Bagh" means garden.',                                  ur: 'Bagh ka matlab garden.' },
      { word: 'GHAR',     en: '"Ghar" means home.',                                    ur: 'Ghar ka matlab home.' },
      { word: 'DOST',     en: '"Dost" means friend.',                                  ur: 'Dost ka matlab friend.' },
      { word: 'CHAY',     en: '"Chay/Chai" means tea — Pakistan\'s national drink.',   ur: 'Chay/Chai ka matlab tea, Pakistan ka national drink.' },
      { word: 'BAARISH',  en: '"Baarish" — slightly longer spelling of "rain".',       ur: 'Baarish — "Barish" ki lambi spelling.' },
      { word: 'PAANI',    en: '"Paani" means water.',                                  ur: 'Paani ka matlab water.' },
      { word: 'ROSHNI',   en: '"Roshni" means light.',                                 ur: 'Roshni ka matlab light.' },
      { word: 'SOORAJ',   en: '"Sooraj" means sun.',                                   ur: 'Sooraj ka matlab sun.' },
      { word: 'CHAND',    en: '"Chand" means moon.',                                   ur: 'Chand ka matlab moon.' },
      { word: 'SITARA',   en: '"Sitara" means star.',                                  ur: 'Sitara ka matlab star.' },
      { word: 'PHOOL',    en: '"Phool" means flower.',                                 ur: 'Phool ka matlab flower.' },
      { word: 'PARWAZ',   en: '"Parwaaz" means flight.',                               ur: 'Parwaaz ka matlab flight.' },
      { word: 'KHUSHI',   en: '"Khushi" means happiness.',                             ur: 'Khushi ka matlab happiness.' },
      { word: 'PYAAR',    en: '"Pyaar" means love.',                                   ur: 'Pyaar ka matlab love.' },
      { word: 'WAQT',     en: '"Waqt" means time.',                                    ur: 'Waqt ka matlab time.' },
      { word: 'MADAD',    en: '"Madad" means help.',                                   ur: 'Madad ka matlab help.' },
      { word: 'SADAQAT',  en: '"Sadaqat" means truthfulness or honesty.',              ur: 'Sadaqat ka matlab sachayi ya honesty.' },
      { word: 'IMAANDAR', en: '"Imaandar" means honest.',                              ur: 'Imaandar ka matlab honest.' },
      { word: 'MOHABBAT', en: '"Mohabbat" means love (deep).',                         ur: 'Mohabbat ka matlab gehri love.' },
      { word: 'SACHAYI',  en: '"Sachayi" means truth.',                                ur: 'Sachayi ka matlab truth.' },
      { word: 'INSAAF',   en: '"Insaaf" means justice.',                               ur: 'Insaaf ka matlab justice.' },
      { word: 'TALEEM',   en: '"Taleem" means education.',                             ur: 'Taleem ka matlab education.' },
      { word: 'AMAN',     en: '"Aman" means peace.',                                   ur: 'Aman ka matlab peace.' },
      { word: 'UMEED',    en: '"Umeed" means hope.',                                   ur: 'Umeed ka matlab hope.' },
      { word: 'KHAWAB',   en: '"Khawaab" means dream.',                                ur: 'Khawaab ka matlab dream.' },
    ],
  },
  {
    key: 'history',
    name: 'Pakistan History',
    emoji: '🕌',
    description: 'Landmarks, dates and movements that shaped the nation.',
    words: [
      { word: 'PAKISTAN', en: 'Pakistan was founded on 14 August 1947 after partition of British India.',                   ur: 'Pakistan 14 August 1947 ko taqseem-e-Hind ke baad qaayam hua.' },
      { word: 'LAHORE',   en: 'The Lahore Resolution of 1940 first formally demanded a separate Muslim state.',             ur: '1940 ki Qarardad-e-Lahore mein pehli baar alag Muslim mulk ka mutalba kiya gaya.' },
      { word: 'KASHMIR',  en: 'Kashmir is the disputed mountain region central to Pakistan-India relations.',                ur: 'Kashmir mutanaza pahaadi ilaqa hai jo Pakistan-India taluqaat ka markaz hai.' },
      { word: 'INDUS',    en: 'The Indus is Pakistan\'s longest river — the cradle of an ancient civilisation.',             ur: 'Indus (Sindh) darya Pakistan ka sab se lamba darya aur qadeem tehzeeb ka markaz hai.' },
      { word: 'MOHENJO',  en: 'Mohenjo-daro is a 5,000-year-old Indus Valley civilisation site in Sindh.',                   ur: 'Mohenjo-daro Sindh mein 5,000 saal purani Indus Valley civilisation ka maqaam hai.' },
      { word: 'TAXILA',   en: 'Taxila was a major centre of learning in the ancient Buddhist era.',                          ur: 'Taxila qadeem Buddhist daur ka aham markaz-e-ilm tha.' },
      { word: 'BADSHAHI', en: 'The Badshahi Mosque in Lahore is one of the largest Mughal mosques in the world.',             ur: 'Lahore ki Badshahi Masjid duniya ki sab se bari Mughal masjido mein se ek hai.' },
      { word: 'MINAR',    en: 'Minar-e-Pakistan in Lahore commemorates the 1940 Pakistan Resolution.',                       ur: 'Minar-e-Pakistan (Lahore) 1940 ki Qarardad-e-Pakistan ki yaadgaar hai.' },
      { word: 'KHILAFAT', en: 'The Khilafat Movement (1919-1924) was a key step toward Muslim political awakening.',         ur: 'Khilafat Tehreek (1919-1924) Muslim siyaasi bedaari ki ahem kadi thi.' },
      { word: 'GANDHARA', en: 'Gandhara was an ancient kingdom in present-day Pakistan, famous for Buddhist art.',           ur: 'Gandhara aaj ke Pakistan mein qadeem hukoomat thi, Buddhist art ke liye mashhoor.' },
      { word: 'HARAPPA',  en: 'Harappa is another Indus Valley civilisation site, found in Punjab.',                          ur: 'Harappa Punjab mein Indus Valley civilisation ka maqaam hai.' },
      { word: 'MUGHAL',   en: 'The Mughal Empire ruled much of South Asia for over 300 years.',                              ur: 'Mughal saltanat ne South Asia par 300 saal se zyada hukoomat ki.' },
      { word: 'ABDALI',   en: 'Ahmad Shah Abdali founded the Durrani Empire and influenced Pakistan\'s history.',             ur: 'Ahmad Shah Abdali ne Durrani saltanat banaayi, Pakistan ki tareekh par asar daala.' },
      { word: 'AKBAR',    en: 'Emperor Akbar of the Mughals expanded the empire across much of South Asia.',                  ur: 'Mughal badshah Akbar ne saltanat ko zyada hisson tak phailaaya.' },
      { word: 'AURANG',   en: 'Aurangzeb was the last great Mughal Emperor, ruling for nearly 50 years.',                    ur: 'Aurangzeb akhri bara Mughal badshah tha, qareeban 50 saal hukmaraan raha.' },
      { word: 'TIPU',     en: 'Tipu Sultan of Mysore fought British expansion and inspired later Muslim leaders.',           ur: 'Mysore ke Tipu Sultan ne British ke khilaaf jang lari, baad ke Muslim qaaideen ko mutaasir kiya.' },
      { word: 'PARTITION',en: 'Partition of 1947 created Pakistan and India out of British India.',                          ur: '1947 ki taqseem ne British Hind se Pakistan aur India banaye.' },
      { word: 'AYUB',     en: 'Field Marshal Ayub Khan ran Pakistan for over a decade beginning in 1958.',                   ur: 'Field Marshal Ayub Khan ne 1958 ke baad daha saal se zyada Pakistan chalaaya.' },
      { word: 'KARGIL',   en: 'The Kargil conflict (1999) was a high-altitude armed clash between India and Pakistan.',      ur: 'Kargil tanaaza (1999) Pakistan-India ke darmiyaan oonchaayi par jang thi.' },
      { word: 'SIACHEN',  en: 'Siachen Glacier is one of the highest battlegrounds in the world.',                            ur: 'Siachen glacier duniya ke sab se oonchay maidaan-e-jang mein se ek hai.' },
      { word: 'KHYBER',   en: 'The Khyber Pass is a famous mountain pass between Pakistan and Afghanistan.',                  ur: 'Khyber Darra Pakistan-Afghanistan ke darmiyaan mashhoor pahaari darra hai.' },
      { word: 'BOLAN',    en: 'The Bolan Pass connects Balochistan to Afghanistan — a historic trade route.',                ur: 'Bolan Darra Balochistan ko Afghanistan se milata hai, tareekhi tijaarat raah.' },
      { word: 'ANARKALI', en: 'Anarkali Bazaar in Lahore is one of South Asia\'s oldest surviving markets.',                  ur: 'Anarkali Bazaar Lahore South Asia ke qadeem tareen bazaaron mein se ek hai.' },
      { word: 'BAGH',     en: 'Shalimar Bagh in Lahore is a famous Mughal garden built in 1641.',                             ur: 'Shalimar Bagh Lahore 1641 mein bana Mughal bagh hai.' },
      { word: 'FAISAL',   en: 'Faisal Mosque in Islamabad is one of the largest mosques in the world.',                       ur: 'Faisal Masjid Islamabad duniya ki sab se bari masajid mein se ek hai.' },
    ],
  },
];

// Quick lookup map: { 'BIRYANI': { en, ur, category } }
const WORD_INDEX = {};
for (const cat of CATEGORIES) {
  for (const w of cat.words) {
    WORD_INDEX[w.word.toUpperCase()] = {
      en: w.en, ur: w.ur, category: cat.name, categoryKey: cat.key,
    };
  }
}

// Pick N words from a category, length-filtered so the grid generator
// receives a coherent set (e.g. 4-7 letters for a bronze board).
function pickWords(categoryKey, count = 6, minLen = 4, maxLen = 9) {
  const cat = CATEGORIES.find((c) => c.key === categoryKey);
  if (!cat) return [];
  const eligible = cat.words.filter((w) => w.word.length >= minLen && w.word.length <= maxLen);
  const shuffled = [...eligible].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((w) => w.word);
}

module.exports = { CATEGORIES, WORD_INDEX, pickWords };
